const re = require('regexpp')
const fs = require('fs-extra')
const http2 = require('http2')
const chalk = require('chalk')
const process = require('process')
const os = require('os')
const _ = require('lodash')
const mini = require('minimatch');
//const esutils = require('esutils')
const jsyaml = require('js-yaml')
//const optionator = require('optionator')
const sprintf = require('sprintf-js')
const console = require('console')
const log = console.log
log(_.add(1, 2))
